# Site settings
title: UW Courses for Molecular Data Scientists
email: dacb -- AT -- uw.edu
description: "UW Courses for Molecular Data Scientists"
url: "http://uwdirect.github.io"
twitter_username: dacbUW
github_username:  UWDIRECT


# Build settings
markdown: kramdown
