name: DSMCER_general_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - scikit-learn
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scipy
  - pytorch
  - optuna
  - codecarbon
  - pip:
    - jupyterlab
