name: DSMCER_general_env
channels:
  - conda-forge
  - defaults
dependencies:
  - codecarbon
  - matplotlib
  - matplotlib-base
  - numpy=1.19
  - optuna
  - pandas
  - pip
  - python=3.9
  - rdkit
  - scikit-learn
  - scipy
  - seaborn
  - xgboost
  - pytorch
  - pip:
    - jupyterlab
